### ISSUE TITLE
Add contributed packages etc for "Checking the package landscape"

### ISSUE THREAD

**Issue by hturner** [hturner/pkg-dev-ctv#5]
Will open PR with some items for this section.

Items considered but not included:
 - [Metacran](https://www.r-pkg.org/): as package search only covers package metadata (title, description, etc) so not as useful for checking for specific functionality. (However, include metacran CRAN mirror).
 - [sos](https://cran.r-project.org/package=sos): questionable value over `utils::RSiteSearch()` - restricts to functions but misses relevant results found by `RSiteSearch(<string>, restrict = "functions")`
 - [Rseek](https://rseek.org/): already covered by https://cran.r-project.org/search.html
 - [Rdocumentation](https://www.rdocumentation.org/): commercial site advertising Datacamp
 - [CRANberries](http://dirk.eddelbuettel.com/cranberries/) - not an efficient way to search package landscape
 - [rrdio.io](https://github.com/rdrr-io/rdrr-issues/issues/121) - some complaints about [docs being out of date](https://github.com/rdrr-io/rdrr-issues/issues/121), may not be that reliable.

**Comment by hturner** [comment]
Committed directly to `main` by mistake: https://github.com/hturner/pkg-dev-ctv/commit/20afd257e363563b5b2e9312e2e622d6a8ef1c49. @llrs or @rsbivand it would be great if you could review and add any comments here - if it looks fine I can close this issue.

**Comment by rsbivand** [comment]
Ok for me.

**Comment by llrs** [comment]
I don't think I touched that section locally don't worry. Great to see some advancement on this. 

I also recommend to include [search.r-project.org](https://search.r-project.org).

Potentially [code.bioconductor.org](https://code.bioconductor.org) for searching on Bioconductor, it is the official git repository (but it doesn't have rendered individual html pages, I could try to add them).

**Comment by hturner** [comment]
Thank both. [search.r-project.org](https://search.r-project.org/) is already mentioned as the search engine used by `utils::RSiteSearch()`. I added [code.bioconductor.org](https://code.bioconductor.org/) and made some minor edits to clarify the scope of https://cran.r-project.org/search.html and https://search.r-project.org/.
